### ISSUE TITLE
Enable CLI installation via pip

### ISSUE THREAD

**Issue by gadomski** [developmentseed/cql2-rs#33]
Over at **stac-rs** I used a separate Python package (https://pypi.org/project/stacrs/ and https://pypi.org/project/stacrs-cli/) and I _think_ we should do the same here, since the CLI is [a separate crate](https://github.com/developmentseed/cql2-rs/tree/main/cli). So that'd be `cql2-cli` on PyPI.

**Comment by kylebarron** [comment]
What's the rationale for having the CLI be separate? It seems like it would be easy enough to ship along with the main Python library?

**Comment by gadomski** [comment]
> What's the rationale for having the CLI be separate? It seems like it would be easy enough to ship along with the main Python library?

I _think_ it comes from my aversion to **click** being pulled in to Python libs when you don't want it — in the same manner, if we don't need **clap** in our Python package let's not include it. However, the downside is that we take up two packages instead of one, and folks might be surprised when the `pip install cql2` _doesn't_ come with a CLI.

Really happy w/ either, I don't have a strong preference.

**Comment by kylebarron** [comment]
I assume that `clap` is relatively small. I doubt it increases the bundle size of the wheels much at all. I figure unless you have _big_ dependencies that you need to keep separate, the simplicity of having a single wheel building process is preferred.
