### ISSUE TITLE
Invalid parse while combining AND and OR clauses

### ISSUE THREAD

**Issue by antoine-de** [developmentseed/cql2-rs#44]
Hi, thanks a lot for this project.

I try using it, but I'm stuck with what I think is an invalid parsing.

Here is a minimal example: 

```rust
use cql2::Expr;

pub fn main() {
    let s = "(floors>5 AND material='brick') OR swimming_pool=true";

    let query = s.parse::<Expr>().expect("should be valid query");

    assert_eq!(
        query.to_text().unwrap(),
        r#"(("floors" > 5) AND ("material" = 'brick')) OR ("swimming_pool" = true)"#
    );
}

```

```
thread 'main' panicked at examples/test.rs:8:5:
assertion `left == right` failed
  left: "((\"floors\" > 5) AND (\"material\" = 'brick') AND (\"swimming_pool\" = true))"
 right: "((\"floors\" > 5) AND (\"material\" = 'brick')) OR (\"swimming_pool\" = true)"
 ```

The `AND`/`OR` combination becomes only 2 `AND`.

The example is from `fixtures/test/example17.txt`: `(floors>5 AND material='brick') OR swimming_pool=true`, but strangely it's not the same as the  `tests/expected/text/example17.txt` (and I think it's because this file is generated).

**Comment by gadomski** [comment]
@bitner I took a stab but I don't grok the parser well enough ATM, so I'm unassigning myself. I put a failing test up in https://github.com/developmentseed/cql2-rs/pull/45.

**Comment by antoine-de** [comment]
great, thanks, it works as expected 👍
